import time
from typing import Dict, Any, List
from src.config import log_agent, Colors, Config

class RemediationAgent:
    def __init__(self):
        self.name = "Remediation-Reporting-Agent"

    def run(self, state: Dict[str, Any]) -> None:
        log_agent(self.name, "Generating audit report and automated patch configuration scripts...", Colors.GREEN)
        time.sleep(1.5)

        # 1. Generate Markdown Report
        report_content = f"""# Agentic Security Audit Report
Generated by **ASAF-SOC Autonomous Agentic Auditor**  
Scope: `{state['target_scope']}`  
Timestamp: {time.strftime("%Y-%m-%d %H:%M:%S UTC")}

---

## 1. Executive Summary
During the automated audit of the subnet scope `{state['target_scope']}`, the Agent system discovered **{len(state['assets'])}** active hosts. Deep inspection of service banners revealed **{len(state['vulnerabilities'])}** High-severity vulnerabilities. Active remediation plans are required to align with security frameworks.

---

## 2. Discovered Asset Inventory
"""
        for asset in state["assets"]:
            report_content += f"""
### Host: {asset['hostname']}
* **IP Address:** `{asset['ip']}`
* **Operating System:** `{asset['os']}`
* **Criticality:** `{asset['criticality']}`
* **Exposed Services:**
"""
            for service in asset["services"]:
                report_content += f"  - Port `{service['port']}` ({service['service']}) - `{service['version']}`\n"

        report_content += "\n---\n\n## 3. Vulnerability Findings & Risk Vector Details\n"
        for vuln in state["vulnerabilities"]:
            report_content += f"""
### {vuln['cve']}: {vuln['title']}
* **Severity:** `{vuln['severity']}` (CVSS: {vuln['cvss']})
* **Target:** `{vuln['hostname']}` (`{vuln['ip']}`)
* **Service:** `{vuln['service']}`
* **Description:** {vuln['description']}
* **Recommended Mitigation:** {vuln['fix']}
"""

        report_content += "\n---\n\n## 4. Compliance Framework Gaps\n"
        for gap in state["compliance_gaps"]:
            report_content += f"""
### Audit Deficiencies for {gap['vulnerability']} on {gap['target_host']}
* **NIST SP 800-53 Mapping:** `{gap['impacted_frameworks']['NIST']}`
* **CIS Controls Mapping:** `{gap['impacted_frameworks']['CIS']}`
* **GDPR Compliance Status:** `{gap['impacted_frameworks']['GDPR']}`
* **Remediation Action:** {gap['audit_recommendation']}
"""

        # Save Report
        with open(Config.REPORT_OUTPUT_PATH, "w") as f:
            f.write(report_content)
        log_agent(self.name, f"Saved Audit Report to: {Colors.CYAN}{Config.REPORT_OUTPUT_PATH}{Colors.ENDC}", Colors.GREEN)

        # 2. Generate Ansible Remediation Playbook
        ansible_playbook = """---
- name: ASAF-SOC Auto-Remediation Playbook
  hosts: all
  become: yes
  tasks:
"""
        for vuln in state["vulnerabilities"]:
            if "OpenSSL" in vuln["title"]:
                ansible_playbook += f"""
    # Remediation for {vuln['cve']} on {vuln['hostname']}
    - name: Ensure OpenSSL package is upgraded to latest secure version
      ansible.builtin.package:
        name: openssl
        state: latest
      when: ansible_host == '{vuln['ip']}'
"""
            elif "PostgreSQL" in vuln["title"]:
                ansible_playbook += f"""
    # Remediation for {vuln['cve']} on {vuln['hostname']}
    - name: Ensure PostgreSQL server package is upgraded to secure version
      ansible.builtin.package:
        name: postgresql-server
        state: latest
      when: ansible_host == '{vuln['ip']}'
"""

        with open(Config.PLAYBOOK_OUTPUT_PATH, "w") as f:
            f.write(ansible_playbook)
        log_agent(self.name, f"Saved Ansible Remediation Playbook to: {Colors.CYAN}{Config.PLAYBOOK_OUTPUT_PATH}{Colors.ENDC}", Colors.GREEN)
